name: code-style

on:
  pull_request:
    branches:
      - main

jobs:
  python-code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          make init-lint
      - name: Run linting
        run: |
          make lint-python
  rust-code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        run: |
          rustup update
      - name: Run Tests
        run: |
          make lint-rust