name: tests-suite

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write

jobs:
  tests-suite-by-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make init-test
      - name: Run tests
        run: |
          make test